# 1. build the image
# sudo docker compose up --build
# 2. run the container
# sudo docker compose up -d
# 3. attach to the container
# sudo docker exec -it ubuntu_container bash      

services:
  my_ubuntu_servicce:
    # image: ubuntu:latest
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu_container
    tty: true
    command: tail -f /dev/null  # Keeps the container running
    volumes:
      - ./shared_ubuntu_container:/root/shared_ubuntu_container  